'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Accessories

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblAccessoryMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessoryMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfAccessoryProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAccessoryProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfNextUpProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNextUpProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtAccessorySKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessorySKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccessoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccessoryBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccessoryDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtAccessoryQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccessoryPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckAccessoryIsOnSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAccessoryIsOnSale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAccessorySalePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessorySalePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSaleStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaleStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSaleEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaleEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuAccessoryImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuAccessoryImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ckAccessoryFeaturedItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAccessoryFeaturedItem As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlShowItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShowItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReleaseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReleaseDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveAccessory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAccessory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteAccessory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteAccessory As Global.System.Web.UI.WebControls.Button
End Class
