'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Apparel

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblApparelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApparelMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfApparelProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfApparelProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtApparelSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApparelSKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApparelNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApparelNames As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApprarelDescriptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApprarelDescriptions As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''XS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''XL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''XXL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XXL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''XXXL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XXXL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApparelPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApparelPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckApparelIsOnSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckApparelIsOnSale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtApparelSalePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApparelSalePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuApprelImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuApprelImg As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ckApparelIsFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckApparelIsFeatured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlShowItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShowItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveApprel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveApprel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteApparel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteApparel As Global.System.Web.UI.WebControls.Button
End Class
