'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cigars

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfCigarProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCigarProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCigarSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarSKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtCigarLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarLength As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarRing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarRing As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarBoxCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarBoxCount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarBoxQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarBoxQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarSingleQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarSingleQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarBoxPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarBoxPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCigarSinglePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCigarSinglePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckCigarIsBoxSaleOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCigarIsBoxSaleOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckCigarIsSingleSaleOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCigarIsSingleSaleOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''fuCigarImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuCigarImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSaveCigar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCigar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteCigar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCigar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCigarMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCigarMessage As Global.System.Web.UI.WebControls.Label
End Class
