'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Coffee

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblCoffeeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoffeeMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfCoffeeProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCoffeeProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCoffeeSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeSKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtCoffeePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeRoast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeRoast As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeBody As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoffeeQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuCoffeeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuCoffeeImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ckCoffeeIsOnSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCoffeeIsOnSale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCoffeeSalePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoffeeSalePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckCoffeeIsFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCoffeeIsFeatured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveCoffee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCoffee As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteCoffee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCoffee As Global.System.Web.UI.WebControls.Button
End Class
