'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PipeTobacco

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblPipeTobaccoMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPipeTobaccoMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfPipeTobaccoProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPipeTobaccoProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtPipeTobaccoSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoSKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtPipeTobacco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobacco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoStyle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoCut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoCut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoStrength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoStrength As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeTobaccoPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckPipeTobaccoIsOnSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPipeTobaccoIsOnSale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPipeTobaccoSalePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeTobaccoSalePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckPipeTobaccoIsFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPipeTobaccoIsFeatured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''fuPipeTobaccoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuPipeTobaccoImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSavePipeTobacco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePipeTobacco As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeletePipeTobacco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePipeTobacco As Global.System.Web.UI.WebControls.Button
End Class
