'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Pipes

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfPipeProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPipeProductID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtPipeSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeSKU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtPipeMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeMaterial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeBodyShape control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeBodyShape As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeStemShape control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeStemShape As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeBowlFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeBowlFinish As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipeQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipeQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPipePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckPipesIsOnSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPipesIsOnSale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPipesSalePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPipesSalePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuPipeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuPipeImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ckPipesIsFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPipesIsFeatured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSavePipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePipe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeletePipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePipe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPipeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPipeMessage As Global.System.Web.UI.WebControls.Label
End Class
